---
-
  hosts: windows
  gather_facts: false
  collections:
   - ansible.windows

  vars:
    username: ''
    user_password: ''

  tasks:
    - name: Reset local user password
      ansible.windows.win_user:
       name: "{{ username }}"
       password: "{{ user_password }}"
