---
-
  hosts: windows
  gather_facts: false
  collections:
   - ansible.windows

  vars:
    username: ''
    user_password: ''

  tasks:
   ## Add tasks below
    # - name: Reset local user password
    #   ansible.windows.win_user:
    #     name: "{{ username }}"
    #     password: "{{ user_password }}"
