---
- name: Provision System Software
  hosts: Windows_Servers

  tasks:

   - name: Install required software
     chocolatey.chocolatey.win_chocolatey:
      name:
       - 7zip
      state: present