---
- name: Update/Change Reg keys
  hosts: Windows_Servers
  collections:
   - ansible.windows

  vars:
    autoupdate:
    updateaccess:

  tasks:

   - name: Disable Windows update by creating DisableWindowsUpdateAccess
     ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: DisableWindowsUpdateAccess
      data: "{{ updateaccess }}"
      type: dword

   - name: Disable Auto-update on Windows
     ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoUpdate
      data: "{{ autoupdate }}"
      type: dword