---
- name: Listen for events on a webhook
  hosts: all
  
  # Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000
  
  # Define the conditions we are looking for
  rules:
    - name: Which IT seminar are you attending?
      condition: event.payload.message == "DevOpsDays"      
      # Define the action we should take should the condition be met
      action:
        run_job_template:
          name: "Playbook - Say Thanks"
          organization: Default
    - name: Really?
      condition: event.payload.message != "DevOpsDays"
      action:
        debug:
          msg: "Really? {{ event.payload.message }}. Would you like to reconsider?"


### Execute the following command in EDA terminal to test ###
# curl -H 'Content-Type: application/json' -d "{\"message\": \"Cloud Summit\"}" eda.lab.weithenn.org/endpoint
# curl -H 'Content-Type: application/json' -d "{\"message\": \"DevOpsDays\"}" eda.lab.weithenn.org/endpoint
