---
- name: Test AB Testing percentage
  hosts: all
  gather_facts: no

  tasks:
    - name: Testing the split_clients Configuration
      shell: |
        for x in {1..20}; 
        do
          curl 127.0.0.1:8888?token=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1); 
        done
      register: webversion_result

    - name: Print webversion result
      debug:
        var: webversion_result.stdout_lines