---
- name: Send mail from Gamil SMTP
  hosts: lnode01
  connection: local
  vars:
    gmail:
      smtp_server: "smtp.gmail.com"
      username: "{{ Gmail_username }}"
      password: "{{ Gmail_password}}"
      address: "{{ Gmail_address }}"

  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      ansible.builtin.mail:
        host: "{{ gmail.smtp_server }}"
        port: '587'
        username: "{{ gmail.username }}"
        password: "{{ gmail.password }}"
        to: "{{ gmail.address }}"
        subject: Can't not SSH to "{{ inventory_hostname }}"
        body: Can't not SSH to "{{ inventory_hostname }}"
      register: sending_email

    - name: Print sending an e-mail result
      ansible.builtin.debug:
        var: sending_email
