# ==================================================================
# Author:         Weithenn Wang (weithenn at weithenn.org)
# Version:        v0.1 - September 11, 2024
# IT event:       Hello World Dev Conference 2024
# Workshop Name:  從 DevOps 到 SRE, 從 IaC 到 GitOps
# Description:    From DevOps to SRE and from IaC to GitOps
# ==================================================================



---
- name: Hello GitOps Workshop
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Ansible Ping - try to connect to host test
      ping:
      register: pong

    - name: Print ping result
      debug:
        msg: "{{ pong }}"
