# ==================================================================
# Author:         Weithenn Wang (weithenn at weithenn.org)
# Version:        v0.1 - September 11, 2024
# IT event:       Hello World Dev Conference 2024
# Workshop Name:  從 DevOps 到 SRE, 從 IaC 到 GitOps
# Description:    From DevOps to SRE and from IaC to GitOps
# ==================================================================



---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    gmail:
      smtp_server: "smtp.gmail.com"
      username: "{{ Gmail_username }}"
      password: "{{ Gmail_password}}"
      address: "{{ Gmail_address }}"

  tasks:
    # - name: Sending an e-mail using Gmail SMTP servers
    #   mail:
    #     host: "{{ gmail.smtp_server }}"
    #     port: 587
    #     username: "{{ gmail.username }}"
    #     password: "{{ gmail.password }}"
    #     to: "{{ gmail.address }}"
    #     subject: Can't not SSH to "{{ inventory_hostname }}"
    #     body: Can't not SSH to "{{ inventory_hostname }}"
    #   register: sending_email

    - name: Print sending an e-mail result
      debug:
        var: sending_email
