# ==================================================================
# Author:         Weithenn Wang (weithenn at weithenn.org)
# Version:        v0.1 - September 11, 2024
# IT event:       Hello World Dev Conference 2024
# Workshop Name:  從 DevOps 到 SRE, 從 IaC 到 GitOps
# Description:    From DevOps to SRE and from IaC to GitOps
# ==================================================================



---
- name: Configure Nginx container and AB Testing
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    nginx_image: nginx:latest
    nginx_container_name: nginx
    nginx_conf_volume: nginx-conf
    nginx_conf_path: /etc/nginx/
    nginx_src_file: ab_testing_split_client.conf
    nginx_conf_file: /var/lib/docker/volumes/nginx-conf/_data/nginx.conf

  tasks:
    - name: Pull Nginx docker image
      community.docker.docker_image:
        name: "{{ nginx_image }}"
        source: pull

    - name: Create volume for Nginx
      community.docker.docker_volume:
        name: "{{ item }}"
        driver: local
      with_items:
        - "{{ nginx_conf_volume }}"

    - name: Ensure Nginx container is running
      community.docker.docker_container:
        name: "{{ nginx_container_name }}"
        image: "{{ nginx_image }}"
        state: present     
        ports:
          - "8888:80"
        volumes:
          - "{{ nginx_conf_volume }}:{{ nginx_conf_path }}:ro"

    - name: Configure Nginx AB testing percentage
      copy:
        src: "{{ nginx_src_file }}"
        dest: "{{ nginx_conf_file }}"

    - name: Using AWX Survey for AB_Test_Percentage in nginx.conf
      replace:
        path: "{{ nginx_conf_file }}"
        regexp: '100%'
        replace: "{{ AB_Test_Percentage }}"
      notify: Restart Nginx container

  handlers:
    - name: Restart Nginx container
      community.docker.docker_container:
        name: "{{ nginx_container_name }}"
        state: started
        restart_policy: always
