# ==================================================================
# Author:         Weithenn Wang (weithenn at weithenn.org)
# Version:        v0.1 - September 11, 2024
# IT event:       Hello World Dev Conference 2024
# Workshop Name:  從 DevOps 到 SRE, 從 IaC 到 GitOps
# Description:    From DevOps to SRE and from IaC to GitOps
# ==================================================================



---
- name: Verify Nginx container and AB Testing
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Testing the split_clients Configuration
      shell: |
        for x in {1..20}; 
        do
          curl 127.0.0.1:8888?token=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1); 
        done
      register: webversion_result

    - name: Print webversion result
      debug:
        var: webversion_result.stdout_lines
