# ==================================================================
# Author:         Weithenn Wang (weithenn at weithenn.org)
# Version:        v0.1 - September 11, 2024
# IT event:       Hello World Dev Conference 2024
# Workshop Name:  從 DevOps 到 SRE, 從 IaC 到 GitOps
# Description:    From DevOps to SRE and from IaC to GitOps
# ==================================================================



---
- name: Stop and remove Nginx containers, images and volumes
  hosts: all
  gather_facts: no
  become: yes
  vars:
    nginx_image: nginx:latest
    nginx_container_name: nginx
    nginx_conf_volume: nginx-conf

  tasks:
    - name: Stop and remove Nginx containers
      docker_container:
        name: "{{ nginx_container_name }}"
        state: absent

    - name: Remove Nginx docker image
      docker_image:
        name: "{{ nginx_image }}"
        state: absent

    - name: Remove Nginx volume
      docker_volume:
        name: "{{ nginx_conf_volume }}"
        state: absent
