---
- name: Destroy VPC network
  hosts: all
  gather_facts: no
  connection: local
  vars:
    project_id: "{{ lookup('env','GCE_PROJECT') }}"
    gcp_service_account: "{{ lookup('env','GCE_CREDENTIALS_FILE_PATH') }}"

  tasks:
    - name: Destroy Google Cloud VPC networks
      google.cloud.gcp_compute_network:
        name: "{{ VPC_Networks }}"     # Using AWX survey for VPC networks
        auto_create_subnetworks: 'true'
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account }}"
        state: absent