---
- name: Destroy GKE Cluster
  hosts: all
  gather_facts: no
  connection: local
  vars:
    zone: "us-central1-c"
    project_id: "{{ lookup('env','GCE_PROJECT') }}"
    gcp_service_account: "{{ lookup('env','GCE_CREDENTIALS_FILE_PATH') }}"

  tasks:
    - name: Destroy GKE Cluster
      google.cloud.gcp_container_cluster:
        name: "{{ GKE_CLUSTER }}"     # Using AWX survey for GKE Cluster
        location: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account }}"
        state: absent