---
- name: Create a GKE Cluster
  hosts: all
  gather_facts: no
  become: yes
  connection: local
  vars:
    zone: "us-central1-c"
    region: "us-centeral1"
    project_id: "gitops-gke-429911"
#    gcloud_sa_path: "./gcpserviceaccount.json"
    gcloud_service_account: "gke-service@gitops-gke-429911.iam.gserviceaccount.com"
#    credential: "{{lookup('env','HOME') }}/{{gcloud_sa_path}}"
    cluster_name: "gketest02"
    initial_node_count: 1
    disk_size_gb: 100
    disk_type: "pd-ssd"
    machine_type: "e2-medium"

  tasks:
    - name: Create a network
      google.cloud.gcp_compute_network:
        name: network-{{cluster_name}}
        auto_create_subnetworks: 'true'
        project: "{{project_id}}"
        auth_kind: serviceaccount
        service_account_file: "{{credential}}"
        state: present
      register: network

    - name: Create a GKE cluster
      google.cloud.gcp_container_cluster:
        name: "{{ cluster_name }}"
        initial_node_count: "{{ initial_node_count }}"
        location: "{{ zone }}"
        network: "{{ network.name }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credential }}"
        state: present
      register: cluster

    - name: create a node pool
      google.cloud.gcp_container_node_pool:
        name: my-pool-{{ cluster_name }}
        initial_node_count: "{{ initial_node_count }}"
        cluster: "{{ cluster }}"
        config:
          disk_size_gb: "{{ disk_size_gb }}"
          disk_type: "{{ disk_type }}"
          machine_type: "{{ machine_type }}"
        location: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credential }}"
        state: present