---
- name: Capture POSTs from gitea
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:
  rules:
    - name: Update repo
      condition: event.payload is defined
      action:
        debug:



### Execute the following command for Gitea test ###
# cd /home/dragon/EDA-Workshop/gitops-push
# sudo ansible-rulebook --rulebook webhook_test.yaml -i inventory.yaml --print-events